version: "2"
services:
  base:
    build: ./ansible/base/
    image: ansible_base
  master:
    build: ./ansible/master/
    image: ansible_master
    depends_on:
      - host01
      - host02
      - host03
    container_name: master01
    hostname: master01
    command: [ "/usr/sbin/sshd", "-D" ]
    volumes:
      - ansible_vol:/var/ans
      - ./playbooks:/var/ans/playbooks
  host01:
    build: ./ansible/host/
    image: ansible_host
    container_name: host01
    hostname: host01
    command: [ "/var/run.sh" ]
    volumes:
      - ansible_vol:/var/ans
  host02:
    image: ansible_host
    container_name: host02
    hostname: host02
    command: [ "/var/run.sh" ]
    volumes:
      - ansible_vol:/var/ans
  host03:
    image: ansible_host
    container_name: host03
    hostname: host03
    command: [ "/var/run.sh" ]
    volumes:
      - ansible_vol:/var/ans
volumes:
  ansible_vol:
